<?php

namespace AccessoireBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * accessoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accessoireRepository extends \Doctrine\ORM\EntityRepository
{
    public function statistique_accessoire()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT count(*) as nombre,p.Lib_C FROM `accessoire` a INNER JOIN produit p WHERE p.ID_P=a.ID_p GROUP by p.Lib_C";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();

    }
}
