<?php

namespace PieceBundle\Repository;

/**
 * pieceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pieceRepository extends \Doctrine\ORM\EntityRepository
{
}
