<?php

namespace AchatBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * achatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class achatRepository extends \Doctrine\ORM\EntityRepository
{
    public function mise_a_jour()
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "DELETE FROM `achat` WHERE DATEDIFF(DATE_F, NOW()) < 0";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return 1;

    }
}
