<?php

namespace MaitenanceBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * maitenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class maitenanceRepository extends \Doctrine\ORM\EntityRepository
{
    public function return_maitenance_user($ID_U)
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT * FROM `maitenance`  where ID_U = ". $ID_U  ." ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();


    }

    public function mise_a_jour()
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "UPDATE `maitenance` SET `etat`=\"repare\" WHERE DATEDIFF(DATE_F, NOW()) < 0 AND etat =\"en cours de reparation\"";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return 1;

    }

    public function oublier_maitenance()
    {
        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT * FROM `maitenance` where  DATEDIFF(DATE_F, NOW())=3 AND etat=\"non réparé\"";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();

    }

}
