<?php

namespace RatingBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * ratingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ratingRepository extends \Doctrine\ORM\EntityRepository
{
    public function maxrate()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT COUNT(*) as nbr ,p.ID_P,p.Libelle,p.Description,p.Prix,p.Image,p.Lib_C,p.Lib_S FROM rating r INNER JOIN produit p where p.ID_P=r.ID_P  GROUP BY r.ID_P   ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
$c=0;

$tab= $stmt->fetchAll();
for($i=0;$i<sizeof($tab);$i++ )
{
    if ((int)$tab[$i]['nbr'] > $c)
    {
        $hedha=  $tab[$i];
    }
}




        return $hedha;


    }


}
