<?php

namespace VeloBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * VeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloRepository extends \Doctrine\ORM\EntityRepository
{


}
