<?php

namespace ReclamationBundle\Repository;

use Doctrine\DBAL\DBALException;

/**
 * reclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function return_reclamation_user($ID_U)
    {

    $conn = $this->getEntityManager()
        ->getConnection();
    $sql = "SELECT * FROM `reclamation`  where ID_U = ". $ID_U  ." ";

    try {
        $stmt = $conn->prepare($sql);
    } catch (DBALException $e) {
    }
    $stmt->execute();
    return $stmt->fetchAll();


    }
    public function return_reclamations_bien()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT * FROM `reclamation` r INNER JOIN user u  where r.etat = 'Bien' and u.id=r.ID_U ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();


    }
    public function return_reclamations_mauvais()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT * FROM `reclamation` r INNER JOIN user u  where r.etat = 'mauvais' and u.id=r.ID_U ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();


    }
}
