<?php

namespace EvenementBundle\Repository;

/**
 * SponsorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorRepository extends \Doctrine\ORM\EntityRepository
{
}
