<?php

namespace panierBundle\Repository;

/**
 * panierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class panierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT quantite*prix AS subtotale FROM panier GROUP BY id";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();

    }
}