<?php

namespace commandeBundle\Repository;

/**
 * commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDQL()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "INSERT INTO `command`(`id`, `labelle`, `quantite`, `prix`, `subtotale`) SELECT * FROM `panier`";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();


        $conn = $this->getEntityManager()
            ->getConnection();
        $sql2 = "delete from panier";

        try {
            $stmt2 = $conn->prepare($sql2);
        } catch (DBALException $e) {
        }
        $stmt2->execute();

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "select * from command group by id ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function montant()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "SELECT SUM(quantite*prix)+ 8000 AS prix_tot FROM command";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();

    }

    public function aDQL()
    {

        $conn = $this->getEntityManager()
            ->getConnection();
        $sql = "select * from command group by id ";

        try {
            $stmt = $conn->prepare($sql);
        } catch (DBALException $e) {
        }
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
