<?php

namespace SiteBundle\Repository;

/**
 * siteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class siteRepository extends \Doctrine\ORM\EntityRepository
{
}
