imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CategorieBundle/Resources/config/services.yml" }
    - { resource: "@SiteBundle/Resources/config/services.yml" }
    - { resource: "@ProduitBundle/Resources/config/services.yml" }
    - { resource: "@AbonnementBundle/Resources/config/services.yml" }
    - { resource: "@AchatBundle/Resources/config/services.yml" }
    - { resource: "@ReservationBundle/Resources/config/services.yml" }
    - { resource: "@VeloBundle/Resources/config/services.yml" }
    - { resource: "@ReclamationBundle/Resources/config/services.yml" }
    - { resource: "@AccessoireBundle/Resources/config/services.yml" }
    - { resource: "@RatingBundle/Resources/config/services.yml" }
    - { resource: "@PieceBundle/Resources/config/services.yml" }
    - { resource: "@ChatBundle/Resources/config/services.yml" }
    - { resource: "@MaitenanceBundle/Resources/config/services.yml" }
    - { resource: "@EvenementBundle/Resources/config/services.yml" }
    - { resource: "@MobileapiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    image_directory: '%kernel.project_dir%/web/uploads/images'
    templating:
      engines: ['twig', 'php']

framework:
    #esi: ~

    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'

    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    templating:
      engines: ['twig', 'php']
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

knp_snappy:
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
            no-outline: true
            page-size: LETTER
            # Recommended to set UTF-8 as default encoding :)
            encoding: UTF-8
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
   router:
        annotations: false

knp_paginator:
    page_range:                 5          # default page range used in pagination control
    default_options:
        page_name:              page       # page query parameter name
        sort_field_name:        sort       # sort field query parameter name
        sort_direction_name:    direction  # sort direction query parameter name
        distinct:               true       # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:                               # this line
        mailer: fos_user.mailer.twig_swift # this line (from the comment above)
    from_email:
        address: "aymenouerghui17@gmail.com"
        sender_name: "Test App"

fos_message:
    db_driver: orm
    thread_class: AppBundle\Entity\Thread
    message_class: AppBundle\Entity\Message

gregwar_captcha:
    width: 160
    height: 50

vresh_twilio:

    sid: ACce87cf249118c8fe7b077ae54a10209a

    authToken: 49a3d84ce854d2e88c1e55af43b98134

    version: '2010-04-01'

    retryAttempts: 3

# Web Socket Configuration
gos_web_socket:
  server:
    port: 7777        #The port the socket server will listen on
    host: 127.0.0.1   #The host ip to bind to

nomaya_social:
  buttons:
    facebook:
      url:            null
      locale:         "fr_FR"
      send:           false
      width:          300
      showFaces:      false
      layout:         "button_count"

  links:
    facebook:           "http://www.facebook.com/yann.chauvel"
    googleplus:         "https://plus.google.com/105931415830389032796"
  theme:                  'default'
